http:
  routers:
    prompt-database-http:
      rule: "PathPrefix(`/prompt-database`)"
      entryPoints:
        - web
      service: prompt-database
      priority: 10
    
    prompt-database-https:
      rule: "PathPrefix(`/prompt-database`)"
      entryPoints:
        - websecure
      service: prompt-database
      tls: {}
      priority: 10

  services:
    prompt-database:
      loadBalancer:
        servers:
          - url: "http://prompt-database:3000"

